language: cpp

matrix:
  include:
  # GCC on linux        
    - os: linux
      addons:
        apt:    
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    # GCC on macos
    - os: osx
      osx_image: xcode11
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    # CLANG on linux        
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    # clang on macos
    - os: osx
      osx_image: xcode11

before_install:
    - eval "${MATRIX_EVAL}"

install:
    - cmake -H. -BDebug -DCMAKE_BUILD_TYPE=Debug
    - cmake --build Debug
    - cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release
    - cmake --build Release

script:
    - cd Debug && ctest
    - cd ..
    - cd Release && ctest
